### ISSUE TITLE
Cheatsheet

### ISSUE THREAD

**Issue by FarYetNear** [cisagov/Sparrow#20]
Is there a cheat sheet that outlines what one should be looking for in the excel output?

**Comment by suregoforit** [comment]
Having details on what to look for analysis helps. 
For e.g. : Searches for SAML token usage anomaly (UserAuthenticationValue of 16457) in the Unified Audit Logs
What to look for when users found with userauthenticationvalue of 16457. Results shows many users with value 16457.

**Comment by JeffSalisbury** [comment]
The details would be very helpful. The SAML token anomaly is the biggest area where I couldn't find any mention of this value or what it means. We have heard that these are actually  generated by OAuth 2.0 authentication, and not SAML, and that they are likely caused by someone logged into their own O365 tenant who clicks on a link to a file on your O365 tenant. We also believe that it gets recorded as a successful logon with errors even though the user didn't actually successfully logon to your tenant. It would be great to have this confirmed by the CISA author, and to know why these are of concern since something must have caused them to become a focus of the scripts.

**Comment by DeemOnSecurity** [comment]
@suregoforit @JeffSalisbury The 16457 token value is an indicator of unusual token creation that has been flagged as potentially anomalous. Further analysis should be conducted to ensure these tokens are being used legitimately.

**Comment by jh2007** [comment]
Agreed with @FarYetNear an accompanying document to help decipher the result data in the CSV files would be a tremendous help.

**Comment by DeemOnSecurity** [comment]
Documentation can be found in Alert [AA21-008A](https://us-cert.cisa.gov/ncas/alerts/aa21-008a)

**Comment by itsreallynick** [comment]
> What to look for when users found with userauthenticationvalue of 16457. Results shows many users with value 16457.

@suregoforit - to further address continued questions about the above event, I have recommended the [temporary] removal of the logic in question within Pull Request #59 - [Removal of Azure AD UserAuthenticationMethod 16457 logic](https://github.com/cisagov/Sparrow/pull/59). 🍻
